# Dockerfile
FROM golang:1.23 AS builder

# 设置 GOPROXY 环境变量!!!
ARG GOPROXY
ENV GOPROXY=${GOPROXY:-https://mirrors.tencent.com/go/,direct}
ENV GO111MODULE=on

WORKDIR /app
COPY go.mod go.sum ./
# 添加重试逻辑
RUN for i in 1 2 3 4 5; do go mod download && break || sleep 10; done
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/main .
CMD ["/root/main"]
